### ISSUE TITLE
USA only location

### ISSUE THREAD

**Issue by itseoconsulting** [aholkner/matomo-cloudflare-location-provider#2]
At matomo.tld/index.php?module=UserCountry&action=adminIndex I can see the correct CF header based(?) location:
<img width="805" alt="Capture" src="https://user-images.githubusercontent.com/33797903/66091904-4eca3d80-e5bc-11e9-8730-0fdbc57e691c.PNG">

Switching to the Cloudflare location provider results in all visitors from USA:
<img width="433" alt="Capture2" src="https://user-images.githubusercontent.com/33797903/66092038-d6b04780-e5bc-11e9-84bd-1538b35363d2.PNG">

Any suggestions on what I should do to make it reproducible for you?

Is the location provider's result on the geolocation setup page already Cloudflare header-based?

**Comment by aholkner** [comment]
I won't be able to provide any support for this -- the plugin literally just passes the Cloudflare header through to Matomo.

It's possible that your Matomo admin instance has a different Cloudflare routing setup than your actual website.  Otherwise, you'll need to check the HTTP_CF_IPCOUNTRY header in your server logs.

**Comment by itseoconsulting** [comment]
Thanks for your feedback.

If I am right the HTTP IP Country Header arrives correctly
https://matomo.celax.asia/getallheaders.php

Best guess it get lost inside of Matomo.

**Comment by d3vr** [comment]
Sorry to bump an old and closed issue but I'm facing the same problem, have you been able to figure it out @itseoconsulting ?

Thanks.

**Comment by itseoconsulting** [comment]
Nope.

HTTP request headers always included cloudflares request headers but plugin
never picked up anything, apart of setup page, where location was shown
correctly. I never investigated more.

Example headers we see:
HTTP_CF_IPCOUNTRY = ID
HTTP_CF_RAY = 5a37ca5d1a4b01c4-SIN


We use now ip2location with a crontab monthly update script

Works well
